GET http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

###

GET http://localhost:3003/api/blogs/66251c40de0add91d24c3a22 HTTP/1.1
Content-Type: application/json

###

POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY2MjZhNDVmZDNkYWVjZjA2ZDliN2MxOSIsImlhdCI6MTcxMzgyOTA5N30.5-JhctiLIXlnRVYWFtFBpv0uWafOp0wwbkbA_B3V3A8

{"title": "A new post",
  "author": "Marcel Proust",
  "url": "www.newpost.com",
  "likes": "43"}


###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json

{"title": "A second post",
  "author": "Emile Zola",
  "url": "www.newpost.com",
  "likes": "43"}


###
POST http://localhost:3003/api/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY2MjZhNDVmZDNkYWVjZjA2ZDliN2MxOSIsImlhdCI6MTcxMzgxOTY4Nn0.tf46Qz72IAaqExoblDExXObeKKoQxINl6VvokKPxPsA

{"title": "A third post",
  "author": "Marcel Proust",
  "url": "www.newpost.com",
  "likes": "43"}


###
DELETE http://localhost:3003/api/blogs/66251c40de0add91d24c3a22 HTTP/1.1
Content-Type: application/json

###

DELETE http://localhost:3003/api/blogs/6626e19fd43034c1618384dc HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIiLCJpZCI6IjY2MjZhNDVmZDNkYWVjZjA2ZDliN2MxOSIsImlhdCI6MTcxMzgxOTY4Nn0.tf46Qz72IAaqExoblDExXObeKKoQxINl6VvokKPxPsA